-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity HW1 is
  port (
    A: in std_logic;
    B: in std_logic;
    C: in std_logic;
    F: out std_logic);
end HW1;

architecture Behavioral of HW1 is
  signal s0: std_logic;
begin
  F <= ((NOT A AND NOT B) OR (B AND C));
  s0 <= NOT C;
end Behavioral;
