-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DECODER_4 is
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    out_2: out std_logic;
    out_3: out std_logic;
    out_4: out std_logic;
    out_5: out std_logic;
    out_6: out std_logic;
    out_7: out std_logic;
    out_8: out std_logic;
    out_9: out std_logic;
    out_10: out std_logic;
    out_11: out std_logic;
    out_12: out std_logic;
    out_13: out std_logic;
    out_14: out std_logic;
    out_15: out std_logic;
    sel: in std_logic_vector (3 downto 0) );
end DECODER_4;

architecture Behavioral of DECODER_4 is
begin
  out_0 <= '1' when sel = "0000" else '0';
  out_1 <= '1' when sel = "0001" else '0';
  out_2 <= '1' when sel = "0010" else '0';
  out_3 <= '1' when sel = "0011" else '0';
  out_4 <= '1' when sel = "0100" else '0';
  out_5 <= '1' when sel = "0101" else '0';
  out_6 <= '1' when sel = "0110" else '0';
  out_7 <= '1' when sel = "0111" else '0';
  out_8 <= '1' when sel = "1000" else '0';
  out_9 <= '1' when sel = "1001" else '0';
  out_10 <= '1' when sel = "1010" else '0';
  out_11 <= '1' when sel = "1011" else '0';
  out_12 <= '1' when sel = "1100" else '0';
  out_13 <= '1' when sel = "1101" else '0';
  out_14 <= '1' when sel = "1110" else '0';
  out_15 <= '1' when sel = "1111" else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A0: in std_logic;
    A1: in std_logic;
    A2: in std_logic;
    A3: in std_logic;
    F3: out std_logic;
    F2: out std_logic;
    F1: out std_logic;
    F0: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(3 downto 0);
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
begin
  s0(0) <= A0;
  s0(1) <= A1;
  s0(2) <= A2;
  s0(3) <= A3;
  gate0: entity work.DECODER_4
    port map (
      sel => s0,
      out_0 => s1,
      out_1 => s2,
      out_2 => s3,
      out_3 => s4,
      out_4 => s5,
      out_5 => s6,
      out_6 => s7,
      out_7 => s8,
      out_8 => s9,
      out_9 => s10,
      out_10 => s11,
      out_11 => s12,
      out_12 => s13,
      out_13 => s14,
      out_14 => s15,
      out_15 => s16);
  F3 <= (s10 OR s9 OR s8 OR s7);
  F2 <= (s10 OR s6 OR s5 OR s4);
  F1 <= (s9 OR s6 OR s3);
  F0 <= (s9 OR s8 OR s6 OR s5 OR s3 OR s2);
end Behavioral;
