-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity hw11 is
  port (
    A3: in std_logic;
    A2: in std_logic;
    A1: in std_logic;
    A0: in std_logic;
    F3: out std_logic;
    F2: out std_logic;
    F1: out std_logic;
    F0: out std_logic);
end hw11;

architecture Behavioral of hw11 is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
begin
  s0 <= NOT A3;
  s1 <= NOT A2;
  s2 <= NOT A1;
  s3 <= NOT A0;
  F3 <= NOT (NOT (s0 AND A2 AND A1) AND NOT (A3 AND s1 AND s2));
  F2 <= NOT (NOT (s0 AND s1 AND A1 AND A0) AND NOT (s0 AND A2 AND s2) AND NOT (A3 AND s1 AND s2 AND A0));
  F1 <= NOT (NOT (s0 AND s1 AND A1 AND s3) AND NOT (s0 AND A2 AND s2 AND A0) AND NOT (A3 AND s1 AND s2 AND s3));
  F0 <= NOT (NOT (s0 AND s2 AND A0) AND NOT (s0 AND s1 AND A1 AND s3) AND NOT (s0 AND A2 AND s2) AND NOT (s0 AND A2 AND A0) AND NOT (A3 AND s1 AND s2 AND s3));
end Behavioral;
